### ISSUE TITLE
Error when 'pip3 install faster-than-requests'

### ISSUE THREAD

**Issue by jaredliw** [juancarlospaco/faster-than-requests#31] opened 2019-11-02 15:04 UTC
pip3 install faster-than-requests --isolated --disable-pip-version-check --no-cache-dir --no-binary :all:
Collecting faster-than-requests
  Downloading https://files.pythonhosted.org/packages/57/86/c1645359414b586757cdaee3c8baa684c0ab7fc309ed640998d2f94a3aae/faster_than_requests-0.5.zip (271kB)
     |████████████████████████████████| 276kB 168kB/s
Skipping wheel build for faster-than-requests, due to binaries being disabled for it.
Installing collected packages: faster-than-requests
    Running setup.py install for faster-than-requests ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jared\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jared\\AppData\\Local\\Temp\\pip-install-6sakfd80\\faster-than-requests\\setup.py'"'"'; __file__='"'"'C:\\Users\\jared\\AppData\\Local\\Temp\\pip-install-6sakfd80\\faster-than-requests\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg install --record 'C:\Users\jared\AppData\Local\Temp\pip-record-ex530ewm\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\jared\AppData\Local\Temp\pip-install-6sakfd80\faster-than-requests\
    Complete output (21 lines):
    running install
    running build
    running build_ext
    building 'faster_than_requests' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ic:\users\jared\anaconda3\include -Ic:\users\jared\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt" /Tcfaster_than_requests_faster_than_requests.c /Fobuild\temp.win-amd64-3.7\Release\faster_than_requests_faster_than_requests.obj -flto -ffast-math -march=native -O3
    cl : Command line warning D9002 : ignoring unknown option '-flto'
    cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    faster_than_requests_faster_than_requests.c
    faster_than_requests_faster_than_requests.c(3412): error C2143: syntax error: missing ')' before '('
    faster_than_requests_faster_than_requests.c(3412): error C2059: syntax error: ')'
    faster_than_requests_faster_than_requests.c(3412): error C2146: syntax error: missing ')' before identifier 'NimMainInit'
    faster_than_requests_faster_than_requests.c(3412): error C2091: function returns function
    faster_than_requests_faster_than_requests.c(3412): error C2061: syntax error: identifier 'NimMainInit'
    faster_than_requests_faster_than_requests.c(3412): error C2059: syntax error: ';'
    faster_than_requests_faster_than_requests.c(3412): error C2059: syntax error: '<parameter-list>'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\jared\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jared\\AppData\\Local\\Temp\\pip-install-6sakfd80\\faster-than-requests\\setup.py'"'"'; __file__='"'"'C:\\Users\\jared\\AppData\\Local\\Temp\\pip-install-6sakfd80\\faster-than-requests\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg install --record 'C:\Users\jared\AppData\Local\Temp\pip-record-ex530ewm\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

*********************************************************************************************************
I have GCC downloaded but I still have this error. Can somebody help me?

**Comment by juancarlospaco** [comment] 2019-11-02 19:10
Git clone the repo and compile https://github.com/juancarlospaco/faster-than-requests#windows

**Comment by jaredliw** [comment] 2019-11-03 02:20
I have tried cloning to Anaconda3 site-packages using Git Bash. After compiling in python, it said:
import faster_than_requests as requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'faster_than_requests'

**Comment by jaredliw** [comment] 2019-11-03 02:25
![image](https://user-images.githubusercontent.com/57293776/68079432-474cbd00-fe24-11e9-8eae-1b33583f2167.png)

**Comment by juancarlospaco** [comment] 2019-11-03 02:51
You Git cloned.
You do not compiled.

**Comment by jaredliw** [comment] 2019-11-03 04:04
By how?

**Comment by juancarlospaco** [comment] 2019-11-03 04:24
```
cd
git clone https://github.com/juancarlospaco/faster-than-requests.git
cd faster-than-requests/src/
nimble install nimpy
nim c -d:ssl -d:release --app:lib --out:faster_than_requests.pyd faster_than_requests.nim
```

It is literally shown on the screenshot.
:slightly_smiling_face:

**Comment by jaredliw** [comment] 2019-11-03 04:56
Oops... Thanks for your patience. But I can't run 'nimble', how should I install it?

**Comment by juancarlospaco** [comment] 2019-11-03 05:39
[You need to install it](https://nim-lang.org/install.html)
:slightly_smiling_face:

**Comment by jaredliw** [comment] 2019-11-03 06:20
Sorry, error again.

$ nim c -d:ssl -d:release --app:lib --out:faster_than_requests.pyd faster_than_requests.nim
Hint: used config file 'C:\nim-1.0.2\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\jared\Anaconda3\Lib\site-packages\faster-than-requests\src\faster_than_requests.nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: faster_than_requests [Processing]
Hint: httpclient [Processing]
Hint: net [Processing]
Hint: nativesockets [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: time_t [Processing]
Hint: sets [Processing]
Hint: hashes [Processing]
Hint: monotimes [Processing]
Hint: openssl [Processing]
Hint: uri [Processing]
Hint: base64 [Processing]
Hint: mimetypes [Processing]
Hint: strtabs [Processing]
Hint: random [Processing]
Hint: httpcore [Processing]
Hint: tables [Processing]
Hint: streams [Processing]
Hint: asyncnet [Processing]
Hint: asyncdispatch [Processing]
Hint: heapqueue [Processing]
Hint: lists [Processing]
Hint: asyncstreams [Processing]
Hint: asyncfutures [Processing]
Hint: deques [Processing]
Hint: cstrutils [Processing]
Hint: asyncfile [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: parsejson [Processing]
Hint: nimpy [Processing]
Hint: complex [Processing]
Hint: py_types [Processing]
Hint: py_utils [Processing]
Hint: py_lib [Processing]
Hint: sequtils [Processing]
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -fno-ident -flto -ffast-math -march=native -mtune=native -fsingle-precision-constant -O3 -fno-strict-aliasing  -IC:\nim-1.0.2\lib -IC:\Users\jared\Anaconda3\Lib\site-packages\faster-than-requests\src -o C:\Users\jared\nimcache\faster_than_requests_r\stdlib_assertions.nim.c.o C:\Users\jared\nimcache\faster_than_requests_r\stdlib_assertions.nim.c' failed with exit code: 1

In file included from C:\Users\jared\nimcache\faster_than_requests_r\stdlib_assertions.nim.c:9:
C:\nim-1.0.2\lib/nimbase.h:457:13: error: size of array 'Nim_and_C_compiler_disagree_on_target_architecture' is negative
 typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by juancarlospaco** [comment] 2019-11-03 06:50
is your Windows 64Bit?.
is your Python 64Bit?.
is your Nim 64Bit?.

**Comment by juancarlospaco** [comment] 2019-11-03 06:51
It basically says that something on your PC is not 64Bit.

**Comment by jaredliw** [comment] 2019-11-03 06:57
![image](https://user-images.githubusercontent.com/57293776/68081528-3747d400-fe4a-11e9-81cd-f3a4fc44dc87.png)
All of them are 64bit, am I right?

**Comment by jaredliw** [comment] 2019-11-03 07:01
![image](https://user-images.githubusercontent.com/57293776/68081558-be954780-fe4a-11e9-9bf6-277aac76d702.png)
Oh, seems like my minGW is 32Bit, does it affect?

**Comment by juancarlospaco** [comment] 2019-11-03 07:07
Yep, that.
Theres no reason to install 32Bit on anything nowadays, everything after year 2000 is 64Bit.

**Comment by jaredliw** [comment] 2019-11-03 09:33
Still the same error.
![image](https://user-images.githubusercontent.com/57293776/68082435-995b0600-fe57-11e9-9938-9a9f0c4dfbe6.png)

**Comment by juancarlospaco** [comment] 2019-11-03 09:59
GCC, not G++.
Forget G++, check GCC.

**Comment by jaredliw** [comment] 2019-11-03 10:14
I don't think I have rebooted before.
I just update my conda, but it changed nothing.

**Comment by jaredliw** [comment] 2019-11-03 10:15
I can't find a way to check whether Anaconda is 32bit or 64bit.

**Comment by jaredliw** [comment] 2019-11-03 10:29
I try to install minGW again, I think there is some problems here (although I have installed it twice).

**Comment by jaredliw** [comment] 2019-11-03 10:46
Yes, it works.
![image](https://user-images.githubusercontent.com/57293776/68083961-3cb51680-fe6a-11e9-98a9-b39422c42ca6.png)

**Comment by jaredliw** [comment] 2019-11-03 13:18
Tq very much. Thanks for your patience and thank you that you are willing to teach me step by step. All the things work now.
![image](https://user-images.githubusercontent.com/57293776/68085780-852aff00-fe7f-11e9-88d0-a8bfbd1c4449.png)

**Comment by jaredliw** [comment] 2019-11-03 14:04
I would like to say, it is really really fast..........
I found that the requests will hang for about 10 secs after hundreds of requests. it will be a big deal for me as I need to run thousands and thousands of requests. Sir, how can I make this smoother?

**Comment by juancarlospaco** [comment] 2019-11-03 15:11
Post the whole command you used to compile successfully. 

Good that it worked, and you learn new stuff !. 
On the future we want to add more Scrapper oriented features.

**Comment by jaredliw** [comment] 2019-11-04 07:30
This is my code:
`import faster_than_requests.src.faster_than_requests as requests

s_month = [2,4,6,9,11] #months which has less than 31 days 
for m in range(1, 13): #month
    for date in range(1, 32): #date
        if m in s_month and date == 31:
            continue
        elif m == 2 and date >= 29:
            continue
        for x in range(0, 2000, 2):
            id_num = '{:0>2}{:0>2}{:0>4}'.format(m, date, x)
            u = 'https://xxx.com/xxx.php?idn={}'.format(id_num)
            try:
                info = requests.get2str(u)
            except:
                print('\nError')
            print(info, id_num, end='\r')`

**Comment by jaredliw** [comment] 2019-11-04 07:46
Today is better, won't hang too much. But if I run multiple programmes, the performance drops a bit (Hang a bit).

**Comment by juancarlospaco** [comment] 2019-11-04 09:51
It seems you are hitting that API too fast, maybe wait a second or half, the server is cutting you off.

I was saying the command you used to compile but yeah.

**Comment by jaredliw** [comment] 2019-11-04 12:54
Ok, thank you. You have been so helpful!!

**Comment by jaredliw** [comment] 2019-11-04 13:06
Sorry, another idea pops in my mind. Can I make a code to change my identity to confuse the server so that it does not think that the requests are from one computer??

**Comment by juancarlospaco** [comment] 2019-11-04 13:45
Server has your IP.

**Comment by jaredliw** [comment] 2019-11-04 13:53
I had found a way to change IP, but is it possible??
Link: https://www.youtube.com/watch?v=3OFwxkxN_HI&feature=youtu.be

**Comment by jaredliw** [comment] 2019-11-04 13:56
Any other things that affect this?? Proxy??

**Comment by juancarlospaco** [comment] 2019-11-04 14:15
Linux is a different operating system, that you install formatting the disk, but maybe you can run it inside VirtualBox.

**Comment by juancarlospaco** [comment] 2019-11-05 12:03
So this is going kind of Off-Topic.
Theres other places to get help about Linux, better than we can offer here.
On the future we will add more Scrapper-like features.
Closing for now, sorry. 
:slightly_smiling_face:

**Closed by juancarlospaco** 2019-11-05 12:03 UTC
Labels: question

**Comment by jaredliw** [comment] 2019-11-05 13:13
I have tried it. I changed the IP location to the US and I can't even more access to the URL (I just remembered that this website is only available to my country).
@juancarlospaco Any ideas from you that can change my identity when requesting??

**Comment by Nightingale131** [comment] 2019-12-15 19:28
Hi, I get a problem while installing - it freezes completly at this point:

```
(base) C:\Users\thoma>pip install faster_than_requests
Collecting faster_than_requests
  Using cached https://files.pythonhosted.org/packages/90/15/72ffe29bf34b40b4b9881a89e0fbbf9d22ea0b493681965fd08ce1fafa7b/faster_than_requests-0.9.2.zip
Building wheels for collected packages: faster-than-requests
  Building wheel for faster-than-requests (setup.py) ... -
```

**Comment by cokeless** [comment] 2020-04-18 23:14
everything installed successfully, using windows 10 x64 ofc, but when i try to import it it says it was not found. i restarted my computer multiple times just to make sure. Any reason?

**Comment by benostein** [comment] 2020-05-25 10:56
> everything installed successfully, using windows 10 x64 ofc, but when i try to import it it says it was not found. i restarted my computer multiple times just to make sure. Any reason?

I'm getting the exact same issue, did you manage to fix the problem?

**Comment by DeviJv** [comment] 2021-05-03 07:21
![Screenshot (3)](https://user-images.githubusercontent.com/26791396/116850439-8557a800-aba5-11eb-9d56-b43ee988603e.png)

HELP ME :( :(

**Comment by juancarlospaco** [comment] 2021-05-03 15:51
> ![Screenshot (3)](https://user-images.githubusercontent.com/26791396/116850439-8557a800-aba5-11eb-9d56-b43ee988603e.png)

The problem is in the screenshot clearly, as I said the `.pyd` needs to be in the same folder as you are running your `.py` file.

- `C:/Users/WhatUpTime/faster-than-requests/faster_than_requests/faster_than_requests.pyd`
- `C:/Users/WhatUpTime/faster-than-requests/faster_than_requests/examples/example.py`
- `C:/Users/WhatUpTime/faster-than-requests/faster-than-requests/example.py`

This is just how folders work.

**Comment by juancarlospaco** [comment] 2021-05-03 15:56
> ```
> (base) C:\Users\thoma>pip install faster_than_requests
> Collecting faster_than_requests
>   Using cached https://files.pythonhosted.org/packages/90/15/72ffe29bf34b40b4b9881a89e0fbbf9d22ea0b493681965fd08ce1fafa7b/faster_than_requests-0.9.2.zip
> Building wheels for collected packages: faster-than-requests
>   Building wheel for faster-than-requests (setup.py) ... -
> ```

It is a PIP bug, the documentation mentions a few parameters you can pass to PIP so it works properly.

` --disable-pip-version-check --no-cache-dir --no-binary :all: `
